# Generated by Django 4.2.3 on 2023-07-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='promotions.user'),
        ),
        migrations.CreateModel(
            name='HouseVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_address', models.CharField(max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.user')),
            ],
        ),
    ]
